I48 api keys
PumpkinSeed/heimdall pull request #59
Opened 2021-05-03 09:57 UTC by hajnalandor

2021-05-03 12:59 UTC, borosr requested changes

2021-05-03 12:59 UTC, borosr commented on pkg/client/http/client.go
> +	Token []string
This should be a single token for each heimdall nodes.

2021-05-03 13:05 UTC, borosr requested changes

2021-05-03 13:05 UTC, borosr commented on cmd/flags/flags.go
> +	TokenId = &cli.StringFlag{
We should add it into server cmd to be able to pre-set API key in development mode (--in-memory). Skip it in production mode (if backend is set).

2021-05-03 14:02 UTC, borosr approved these changes

2021-05-03 14:52 UTC, borosr requested changes

2021-05-03 14:52 UTC, borosr commented on pkg/client/http/client.go
> +	if len(o.URLs) != len(o.Token) {
Remove this please.

2021-05-03 15:03 UTC, PumpkinSeed requested changes
- What happens if I don't pass `--id` in-memory mode and server?
- Use Vault's root token
- New token should require previous available root-token
- GRPC use token as well
- Rename id flag

2021-05-03 15:34 UTC, borosr commented
Heimdall can use vault's root and other tokens.

2021-05-05 07:55 UTC, PumpkinSeed approved these changes

2021-05-05 07:56 UTC, merged